CREATE TABLE IF NOT EXISTS teams (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    city VARCHAR(50) NOT NULL,
    short_name VARCHAR(50) NOT NULL,
    logo_url VARCHAR(255) NOT NULL,
    stadium VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    primary_team BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
